p8105\_hw2\_yc3242
================
Youn Kyeong Chang (uni\# yc3242)
October 3, 2018

I used the tidyverse library through the whole problem set.

``` r
library(tidyverse)
```

    ## -- Attaching packages ------------------------------------------------------------------ tidyverse 1.2.1 --

    ## v ggplot2 3.0.0     v purrr   0.2.5
    ## v tibble  1.4.2     v dplyr   0.7.6
    ## v tidyr   0.8.1     v stringr 1.3.1
    ## v readr   1.1.1     v forcats 0.3.0

    ## -- Conflicts --------------------------------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

Problem 1
=========

First, I loaded and cleaned dataset for problem 1.

``` r
nyc_data = 
  read_csv(file = "./hw2_data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line:entry, vending, ada) %>% 
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

This NYC Transit data (`nyc_data`) is composed of *line, station name, its latitude and longitude, routes it serves, entrance type, whether or not you can enter the station, presence of ticket vending machine*, and *ADA compliance*. These variables were selected from `NYC_Transit_Subway_Entrance_And_Exit_Data.csv` original dataset which was followed by `clean_names()` function in the janitor library. After selecting variables process, `entry` variable was converted from character variable to logical variable. The size of the NYC Transit data is 1868 rows and 19 columns. These data are not tidy because columns are values not variables and there are many duplicated rows.

To remove duplicated rows, I used `distinct()` function as below:

``` r
nyc_data = distinct(nyc_data)
```

The **size** of the NYC Transit data is now 684 rows and 19 columns.

### Questions

**1.1. How many distinct stations are there?**

``` r
nyc_data %>% 
  distinct(line, station_name, .keep_all = TRUE) %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   465

There are **465** distinct stations.

**1.2. How many stations are ADA compliant?**

``` r
nyc_data %>% 
  distinct(line, station_name, .keep_all = TRUE) %>% 
  filter(ada == TRUE) %>% 
  count(ada)
```

    ## # A tibble: 1 x 2
    ##   ada       n
    ##   <lgl> <int>
    ## 1 TRUE     84

There are **84** ADA compliant stations.

**1.3. What proportion of station entrances / exits without vending allow entrance?**

``` r
nyc_data %>% 
  filter(vending == "NO") %>% 
  summarise(mean(entry == TRUE))
```

    ## # A tibble: 1 x 1
    ##   `mean(entry == TRUE)`
    ##                   <dbl>
    ## 1                 0.385

The proportion of station entrances / exits without vending allow entrance is **0.385**.

**1.4. How many distinct stations serve the A train?**

To answer the questions 1.4. and 1.5., I reformatted data as below so that route number and route name are distinct variables.

``` r
reform_nyc_data = 
  nyc_data %>%
  gather(key = "route", value = "route_name", route1:route11) %>%  # gather spreading route variables
  separate(route, into = c("remove", "route_number"), sep = 5) %>% 
  select(-remove)
```

And then, I calculated distinct stations serve the A train.

``` r
reform_nyc_data %>% 
  distinct(line, station_name, route_name) %>%
  filter(route_name == "A") %>%
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    60

There are **60** distinct stations serve A train.

**1.5. Of the stations that serve the A train, how many are ADA compliant?**

``` r
reform_nyc_data %>% 
  distinct(line, station_name, route_name, .keep_all = TRUE) %>%
  filter(route_name == "A", ada == "TRUE") %>%
  count()
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1    17

There are **17** ADA compliant distinct stations serve A train.

Problem 2
=========

I I used the readxl library to read `xlsx` file for problem 2.

``` r
library(readxl)
```

### Mr. Trash Wheel

I read and clean the Mr. Trash Wheel sheet as follows.

``` r
trash_data = 
  read_excel(path = "./hw2_data/HealthyHarborWaterWheelTotals2017-9-26.xlsx",
                     sheet = 1, range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>%                              # use reasonable variable names
  filter(!is.na(dumpster)) %>%                            # omit NA data
  mutate(sports_balls = as.integer(round(sports_balls)))  # round and convert sports_ball
```

Before I look at the data in detail, I skimmed the data first.

``` r
trash_data %>% skimr::skim()        
```

    ## Skim summary statistics
    ##  n obs: 216 
    ##  n variables: 14 
    ## 
    ## -- Variable type:character --------------------------------------------------------------------------------
    ##  variable missing complete   n min max empty n_unique
    ##     month       0      216 216   3  11     0       13
    ## 
    ## -- Variable type:integer ----------------------------------------------------------------------------------
    ##      variable missing complete   n  mean     sd p0 p25 p50 p75 p100
    ##  sports_balls       0      216 216 30.44 222.93  2   6  13  22 3288
    ##      hist
    ##  <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ## 
    ## -- Variable type:numeric ----------------------------------------------------------------------------------
    ##            variable missing complete   n     mean        sd      p0
    ##           chip_bags       0      216 216  4189.9   30661.78  330   
    ##     cigarette_butts       0      216 216 88588.89 649029.94 1000   
    ##            dumpster       0      216 216   215      1573.8     1   
    ##       glass_bottles       0      216 216    68.62    502.2     7   
    ##        grocery_bags       0      216 216  3248.58  23778.7   190   
    ##       homes_powered       0      216 216    75.08    549.86    0   
    ##     plastic_bottles       0      216 216  4292.59  31415.63  210   
    ##         polystyrene       0      216 216  5139.51  37611.25  340   
    ##  volume_cubic_yards       0      216 216    31.27    228.72    7   
    ##         weight_tons       0      216 216     6.52     47.71    1.24
    ##                year      15      201 216  2015.38      1.01 2014   
    ##       p25      p50      p75       p100     hist
    ##   1257.5   2140     2822.5   452509    <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##  21000    34000    56000    9567600    <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##     54.75   108.5    162.25   23220    <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##     21       32       45       7411    <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##    820     1556     2377.5   350847    <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##      0       47       59.04    8109    <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##   1322.5   2240     2850     463600    <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##   1665     2635     3420     555067    <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##     15       15       18       3377    <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##      2.71     3.35     3.84     704.44 <U+2587><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581><U+2581>
    ##   2015     2015     2016       2017    <U+2585><U+2581><U+2587><U+2581><U+2581><U+2586><U+2581><U+2583>
    ## 
    ## -- Variable type:POSIXct ----------------------------------------------------------------------------------
    ##  variable missing complete   n        min        max     median n_unique
    ##      date       1      215 216 2014-05-16 2017-08-19 2015-12-02      151

As a result, I found out that the number of month is **13**. Therefore, I used `distinct()` function to look at months variables.

``` r
trash_data %>% distinct(month)
```

    ## # A tibble: 13 x 1
    ##    month      
    ##    <chr>      
    ##  1 May        
    ##  2 June       
    ##  3 July       
    ##  4 August     
    ##  5 September  
    ##  6 October    
    ##  7 November   
    ##  8 December   
    ##  9 January    
    ## 10 February   
    ## 11 March      
    ## 12 April      
    ## 13 Grand Total

As the 13th month, there was a "Grand Total" month at the bottom line. I omitted this row so as not to be considered as one of the observations.

``` r
trash_data <- trash_data %>% filter(month != "Grand Total")
```

-   The **number of observations** is 215.
-   I think the **key variables** are `month` and `year` since in general, we can analyze the total amount of trash or each kind of trash by them.
-   The **median** number of sports balls in a dumpster in 2016 is 26.

### Precipiation data

I read and clean precipitation data for 2016.

``` r
precip_2016 = 
  read_excel(path = "./hw2_data/HealthyHarborWaterWheelTotals2017-9-26.xlsx",
                     sheet = 4, skip = 1) %>% 
  janitor::clean_names() %>%    
  rename(total_precip = total) %>%                    # use reasonable variable names
  filter(!is.na(month) & !is.na(total_precip)) %>%    # omit NA data
  mutate(year = 2016)                                 # add a variable year
```

Next, I read and clean precipitation data for 2017.

``` r
precip_2017 = 
  read_excel(path = "./hw2_data/HealthyHarborWaterWheelTotals2017-9-26.xlsx",
                     sheet = 3, skip = 1) %>% 
  janitor::clean_names() %>% 
  rename(total_precip = total) %>%                  # use reasonable variable names
  filter(!is.na(month) & !is.na(total_precip)) %>%  # omit NA data
  mutate(year = 2017)                               # add a variable year
```

And then, I combined these datasets and converted month to a character variable.

``` r
precip_data = bind_rows(precip_2016, precip_2017) %>% 
              mutate(month = month.name[month])
```

-   The number of observations is 20.
-   In this case, `month` and `year` can be considered as **key variables** since, for example, we can see the trends of precipitation by month and compare the amount of precipitation in years.
-   The total precipitation in 2017 is 29.93(in).
